# Generated by Django 4.1.7 on 2023-02-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visComTwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password_digest', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visComTwo.user')),
                ('visual_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visComTwo.visualcard')),
            ],
        ),
    ]
