# Generated by Django 4.1.7 on 2023-03-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visComTwo', '0002_user_communicationboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationboard',
            name='visual_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visComTwo.visualcard'),
        ),
        migrations.AlterField(
            model_name='visualcard',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
